#!/usr/bin/env bash
ansible-galaxy collection install community.general==7.5.0
ansible-galaxy collection install azure.azcollection==1.15
pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
# ansible-galaxy collection install community.azure
